apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
  #attachement d'un label pour filtrer
  labels:
    app: dispatcher-service
spec:
  selector:
    app: dispatcher-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9003
  type: ClusterIP
  